// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHRXSBmfz2yAoA6TkmuUtnTtDG8-M05k',
    appId: '1:943667235810:android:7f32a0bb92ad024484c7bb',
    messagingSenderId: '943667235810',
    projectId: 'fir-module10-e6ebb',
    // storageBucket: 'fir-module10-e6ebb.firebasestorage.app',
    storageBucket: 'fir-module10-e6ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2YFygS4jripLxeiK1obwil62ZXXdSZFU',
    appId: '1:943667235810:ios:4243ddc1556ec67e84c7bb',
    messagingSenderId: '943667235810',
    projectId: 'fir-module10-e6ebb',
    // storageBucket: 'fir-module10-e6ebb.firebasestorage.app',
    storageBucket: 'fir-module10-e6ebb.appspot.com',
    iosBundleId: 'com.example.firebaseModule10',
  );
}
